### ISSUE TITLE
Interpretation of Benchmark Outputs

### ISSUE THREAD

**Issue by spresman** [ekernf01/perturbation_benchmarking_package#3]
Hi again Eric,
I was able to add my own network to your collection, and wanted to run two benchmarks: varying regression and varying networks. I'm having some trouble interpreting the outputs. From my understanding, the resulting perPert.parquet file for the varying regression benchmark should contain a 'regression_methods' column that's populated by each regression method specified in the respective experiment's metadata JSON. The 'regression_methods' column in the output I obtained is only populated by the last value of the list provided in the metadata JSON (which happens to be 'BayesianRidge'). I'm having the same issue for the varying networks benchmark. Am I misunderstanding the output? I've attached the regression benchmark's JSON. Thanks!

[metadata.json](https://github.com/user-attachments/files/17602674/metadata.json)

**Comment by ekernf01** [comment]
You're right -- that's not what I would expect either. Do you have stdout and stderr logged from that run? Could you also share the result of running `tree` on your output folder?

**Comment by spresman** [comment]
Hey, here are the files for the most recent regression I ran:
[tree.txt](https://github.com/user-attachments/files/17620235/tree.txt)
[stdout.txt](https://github.com/user-attachments/files/17620236/stdout.txt)
[err.txt](https://github.com/user-attachments/files/17620237/err.txt)
[metadata.json](https://github.com/user-attachments/files/17620238/metadata.json)

**Comment by ekernf01** [comment]
OK, this looks pretty good to me. All the predictions got saved, and they all got found and read back into memory for evaluation. The exceptions shown in stdout are safe to ignore and they just mean your output will have some 2d visualizations missing. The only downside to all this positivity -- I have no idea at all where the actual problem lies. Is `evaluationsPerPert.parquet` small enough that you could send it, or send me a dropbox/gdrive link to? My email is eric.kern13@gmail.com if that helps.

**Comment by ekernf01** [comment]
Thanks for your patience, and thanks for sending that file. I wrote this bug recently while working on new evaluation code related to timeseries and embryogenesis data. It should be fixed now in the development version. It also should not affect the version of the code released with our preprint. 

You do not have to re-train all the models. If you reinstall `pereggrn` and run it again, by default `pereggrn` will re-run your evaluations based on the already-saved predictions.
